language: scala

jdk:
  - openjdk9

scala:
  - 2.12.4

branches:
  only:
    - master

build:
  ci:
    - |
      sbt update compileAll coreJS/test:fastOptJS jsShell/test:fastOptJS jsShell/fullOptJS test fmtCheck
      echo "Running for PR '$IS_PULL_REQUEST'"
      if [ "$IS_PULL_REQUEST" == false ]; then
        mkdir gh-pages-files
        cp jsShell/.README-compiled.md gh-pages-files/README.md
        cp LICENSE.md jsShell/{index,repl}.html jsShell/art/favicon.png jsShell/target/scala-2.12/jsshell-opt.js gh-pages-files/
        du -sh gh-pages-files/
        TRANSFER=$(shipctl get_resource_state tacit_runCI)
        echo "Writing to $TRANSFER"
        tar cvfR - gh-pages-files/ > $TRANSFER/transfer.tar
        sha1sum $TRANSFER/transfer.tar
      fi

  cache: true
  cache_dir_list:
    - $HOME/.ivy2
    - $HOME/.sbt

jobs:
  - name: tacit_runCI
    type: runCI
    steps: []

  - name: tacit_ghPagesDeploy
    type: runSh
    steps:
      - IN: tacit_runCI
        switch: on
      - IN: tacit_ciRepo
        switch: off
      - TASK:
          script:
            - |
              TRANSFER=$(shipctl get_resource_state tacit_runCI)
              echo "Reading from $TRANSFER"
              if [ -f $TRANSFER/transfer.tar ]; then
                sha1sum $TRANSFER/transfer.tar
                cat $TRANSFER/transfer.tar | tar xvf -
                git clone git@github.com:tacit-lang/tacit-lang.github.io.git gh-pages
                cd gh-pages
                git config user.name 'Shippable Build'
                git config user.email 'build@shippable.com'
                git rm -rf --ignore-unmatch *
                cp ../gh-pages-files/* .
                git add .
                VERSION=$(shipctl get_resource_env tacit_ciRepo versionName)
                echo "Committing for $VERSION"
                git commit --allow-empty --message "Compiled from $VERSION :robot:"
                git push
              fi
